// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewOfferInput struct {
	UserID      string          `json:"userId"`
	Title       string          `json:"title"`
	Description string          `json:"description"`
	Salary      []*SalaryByRole `json:"salary"`
	PictureURL  string          `json:"pictureUrl"`
}

type NewProfileInput struct {
	UserID     string          `json:"userId"`
	Title      string          `json:"title"`
	About      string          `json:"about"`
	Status     string          `json:"status"`
	Country    string          `json:"country"`
	State      string          `json:"state"`
	City       string          `json:"city"`
	PictureURL string          `json:"pictureUrl"`
	WebsiteURL string          `json:"websiteUrl"`
	Salary     []*SalaryByRole `json:"salary"`
}

type NewUserInput struct {
	Name     string `json:"name"`
	LastName string `json:"lastName"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type SalaryByRole struct {
	Title    string  `json:"title"`
	Min      float64 `json:"min"`
	Max      float64 `json:"max"`
	Currency string  `json:"currency"`
}

type SalaryByRoleResult struct {
	Title    string  `json:"title"`
	Min      float64 `json:"min"`
	Max      float64 `json:"max"`
	Currency string  `json:"currency"`
}
