// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type NewUserInput struct {
	Name     string `json:"name"`
	LastName string `json:"lastName"`
	Email    string `json:"email"`
	Password string `json:"password"`
}
