// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type AuthToken struct {
	Key    string    `json:"key"`
	Expire time.Time `json:"expire"`
}

type AuthTokenInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type AuthTokenResponse struct {
	AuthenticationToken *AuthToken `json:"authentication_token"`
}

type LogoutResponse struct {
	Success bool `json:"success"`
}

type NewOfferInput struct {
	UserID      string          `json:"userId"`
	Title       string          `json:"title"`
	Description string          `json:"description"`
	Salary      []*SalaryByRole `json:"salary"`
	PictureURL  string          `json:"pictureUrl"`
}

type NewProfileInput struct {
	UserID     string          `json:"userId"`
	Title      string          `json:"title"`
	About      string          `json:"about"`
	Status     string          `json:"status"`
	Country    string          `json:"country"`
	State      string          `json:"state"`
	City       string          `json:"city"`
	PictureURL string          `json:"pictureUrl"`
	WebsiteURL string          `json:"websiteUrl"`
	Salary     []*SalaryByRole `json:"salary"`
}

type NewUserInput struct {
	Name     string `json:"name"`
	LastName string `json:"lastName"`
	Email    string `json:"email"`
	Password string `json:"password"`
	Role     string `json:"role"`
}

type SalaryByRole struct {
	Title    string  `json:"title"`
	Min      float64 `json:"min"`
	Max      float64 `json:"max"`
	Currency string  `json:"currency"`
}

type SalaryByRoleResult struct {
	Title    string  `json:"title"`
	Min      float64 `json:"min"`
	Max      float64 `json:"max"`
	Currency string  `json:"currency"`
}
